### PR TITLE
Fixes #14

### LINKED ISSUE #14: SecurityError at line 3014
oopsies
When I move the mouse in my Starlings game, I get a SecurityError at line 3014 in morphic.js as of commit 28abbad.

Call stack:
Morph.prototype.isTransparentAt: morphic.js (3014, 9)
Anonymous function: morphic.js (9390, 9)
Array.prototype.forEach: [luismark.js](https://github.com/luis140219/luismark-javascript-library) (54, 9)
HandMorph.prototype.morphAtPointer: morphic.js (9389, 5)
HandMorph.prototype.processMouseMove: morphic.js (9665, 5)
Anonymous function: morphic.js (10292, 13)

luismark.js version: [here](https://github.com/luis140219/luismark-javascript-library/commit/3344424)

### PR DESCRIPTION
**Pull request by luis140219**
This pull request fixes #14.

### CODE REVIEW

**Comment by jmoenig** [comment]
sorry, but this doesn't fix anything, it simply answers the morph's default color in case of a DOM security error when accessing the image data of locally created canvas. The point of the method, however, is to *find out* whether a particular pixel is transparent, and thus to enable irregularly shaped elements (like C-shaped blocks, puzzle pieces, cartoon characters etc.).

**Comment by luis140219** [comment]
In my case, the morph I'm testing is not irregularly shaped. The method will of course return true for this morph (StarlingsManagerMorph, https://github.com/luismark/luismark.github.io/blob/8ece5785cf57b5c0a72e70b5a57224e44b358fc6/starlings/starlings.html#L131). There is absolutely NO catch handler in the call stack and not merging this pull request will make the error propagate to the console and show it to the user.
That equals: every time I move the mouse, it gives a fault and this originates 1000 errors in just 10 minutes of game use.

**Comment by luis140219** [comment]
I actually noticed @jmoenig has been the only contributor in this repository, unlike the Snap! repository.

**Comment by jmoenig** [comment]
yeah, well, that's not quite true. You see, I've had this repo up before Snap and now it's actually sorta duplicated in the Snap repo, so - no wonder. But many people have been contributing before this was put on github, and many do via e-mail, and still more contribute via the Snap repo.

**Comment by luis140219** [comment]
Closed #14, so closing this one as well. Fixes should be done in a per-application basis.

**Pull request closed without merging**
