### PR TITLE
account for alignment offset in TextMorph.prototype.slotAt

### PR DESCRIPTION
**Pull request by brollb**

### CODE REVIEW

**Comment by jmoenig** [comment]
Thanks, Brian! I love bug reports that come with a fix :-)

**Comment by brollb** [comment]
I actually encountered this because I was looking at making [urls in TextMorphs clickable](https://github.com/NetsBlox/Snap--Build-Your-Own-Blocks/pull/837/files). Is this something that might be of interest to morphic, too?

**Comment by brollb** [comment]
For a little more context, the motivation for this in NetsBlox is because we have a number of different Services/RPCS which use existing datasets/online resources and we would like to enable the students to be able to learn more about the origin of the data, etc. This is especially useful when using NetsBlox in combination with other scientific disciplines. (However, it is also useful for clicking links in the "About" dialog, too.)

For example, here is a screenshot of some (alpha) RPCs for fetching ice core data from NOAA used for exploring climate change in NetsBlox:
DeepinScreenshot_select-area_20191014105708

**Comment by jmoenig** [comment]
Oh, wow. That's something I've avoided taking on myself forever, and it's sure beautiful and *very* useful! Not being able to click on links in Morphic is something really embarrassing, so it's great that you've solved that issue!

Yes, I would welcome your PR to Snap!

**Pull request merged**
